sudo: required
services:
  - docker

before_install:
  - docker build -t napatud/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true napatud/react-test npm test

after_success:
  - docker build -t napatud/multi-client ./client
  - docker build -t napatud/multi-nginx ./nginx
  - docker build -t napatud/multi-server ./server
  - docker build -t napatud/multi-worker ./worker

  #Log in to the docker CLI using docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push napatud/multi-client
  - docker push napatud/multi-nginx
  - docker push napatud/multi-server
  - docker push napatud/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: Multicontainer-env
  bucket_name: elasticbeanstalk-ap-southeast-1-149592319634
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
